/*RELATÓRIO GERAL DE TODOS OS CLIENTES(TELEFONE E ENDERECO)*/

SELECT C.IDCLIENTE,C.NOME,C.SEXO,C.EMAIL,C.CPF,E.RUA,E.BAIRRO,E.CIDADE,E.ESTADO,
		T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE;

/* ATUALIZAR O SEXO DO = 10,11,12,16,17,18,19*/ 

SELECT * FROM CLIENTE
WHERE IDCLIENTE IN (10,11,12,16,17,18,19);

UPDATE CLIENTE SET SEXO = 'F'
 WHERE IDCLIENTE IN (10,11,12,16,17,18,19);
 





/* RELATÓRIO DE HOMENS */

SELECT C.IDCLIENTE,C.NOME,C.SEXO,C.EMAIL,C.CPF,E.RUA,E.BAIRRO,E.CIDADE,E.ESTADO,
		T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';


/* RELATÓRIO DE MULHERES */

SELECT C.IDCLIENTE,C.NOME,C.SEXO,C.EMAIL,C.CPF,E.RUA,E.BAIRRO,E.CIDADE,E.ESTADO,
		T.TIPO,T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';


/* QUANTIDADE DE HOMENS E MULHERES */

SELECT COUNT(*) AS QUANTIDADE,SEXO 
FROM CLIENTE
GROUP BY SEXO;

/* IDS E EMAIL DAS MULHERES QUE MORAM NO CENTRO DO RJ E NAO TENHAM CELULAR */


SELECT 	C.IDCLIENTE,
		IFNULL(C.EMAIL,'******************')AS EMAIL,
		C.NOME,
		C.SEXO,
		T.TIPO,
		E.BAIRRO,
		E.CIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F'
AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO'
AND TIPO ='RES' OR TIPO = 'COM';


/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM RELATÓRIO COM O NOME,EMAIL E TELEFONE CELULAR DOS 
CLIENTES QUE MORAM NO  ESTADO DO RIO DE JANEIRO VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA O PROGRAMADOR */

SELECT C.NOME,C.EMAIL,T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE TIPO = 'CEL' AND ESTADO ='RJ';

/* PARA UMA CAMPANNHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM RELATÓRIO COM O NOME,EMAIL E TELEFONE CELULARDAS 
DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO,VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATÓRIO PARA O PROGRAMADOR */

SELECT DISTINCT C.NOME,C.EMAIL,T.NUMERO AS CELULAR
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F' AND ESTADO ='SP';


